/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.alias.jsonc --include-runtime=false --env-interface=AliasBindings alias-configuration.d.ts` (hash: 711743a0c66c4e27f210e7bb4cba0b59)
interface __BaseEnv_AliasBindings {
	STEM_APP: Fetcher /* cail-stem-splitter-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./alias");
	}
	interface Env extends __BaseEnv_AliasBindings {}
}
interface AliasBindings extends __BaseEnv_AliasBindings {}
