/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=PreviewBindings` (hash: ccd19357cfe9f42221119b823cdf77f2)
interface __BaseEnv_PreviewBindings {
	AUDIO: R2Bucket;
	DB: D1Database;
	REQUEST_LIMIT: RateLimit;
	ASSETS: Fetcher;
	AUTH_MODE: "cail";
	CAIL_BROWSER_ORIGIN: "https://tools.ailab.gc.cuny.edu";
	PUBLIC_BASE_URL: "https://cail-stem-splitter-preview.ailab-452.workers.dev";
	CANONICAL_BASE_URL: "https://stem-splitter.ailab-452.workers.dev";
	ROUTED_AUDIO: "true";
	CF_ACCOUNT_ID: "452c33847cf5cb1e46f391fca32fd1b5";
	R2_BUCKET_NAME: "cail-stem-splitter-preview-audio";
	SEPARATION_BACKEND: "replicate";
	SERVER_AUTO_ENABLED: "false";
	SERVER_AUTO_MODE: "off";
	INSTRUMENT_DISCOVERY_ENABLED: "false";
	QUERY_ISOLATION_ENABLED: "false";
	QUERY_ISOLATION_MODE: "off";
	REMIXER_ENABLED: "false";
	RELEASE: "cloudflare-cuny-sso-20260908";
	ADMISSION_RESOLVER: Service /* entrypoint AdmissionResolver from cail-tools-admission */;
	IDENTITY: Service /* entrypoint WorkerIdentity from cail-doorway */;
	PREVIEW_IDENTITY: Service /* entrypoint WorkerIdentity from cail-doorway */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_PreviewBindings {}
}
interface PreviewBindings extends __BaseEnv_PreviewBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_MODE" | "CAIL_BROWSER_ORIGIN" | "PUBLIC_BASE_URL" | "CANONICAL_BASE_URL" | "ROUTED_AUDIO" | "CF_ACCOUNT_ID" | "R2_BUCKET_NAME" | "SEPARATION_BACKEND" | "SERVER_AUTO_ENABLED" | "SERVER_AUTO_MODE" | "INSTRUMENT_DISCOVERY_ENABLED" | "QUERY_ISOLATION_ENABLED" | "QUERY_ISOLATION_MODE" | "REMIXER_ENABLED" | "RELEASE">> {}
}
